### ISSUE TITLE
Impossible to request for temporal user

### ISSUE THREAD

**Issue by xp-1000** [tidusjar/Ombi#864]
#### Ombi Version:

V 1.10.1

#### Update Branch:

Stable

#### Operating System:

Archlinux

#### Mono Version

 4.6.1.3

#### Problem Description:

The situation is :
Authentification disabled for users
User management settings configured to allow TV and Movie request by default.
No local user created in usermanagement (I just want anybody can type a name and request)
The problem is :
When somebody go the my ombi instance, he can login with any name and is redirected to search tab like before 1.10 update.
But now, when it request a movie, system keep saying: Sorry, you do not have the correct permissions to request a TV Show!
There is no user in user management but like I said I configured user management settings to set default permission to users to request tv and movie.
I have 0 log, only the error message on the web app.
May be linked to https://github.com/tidusjar/Ombi/issues/725
Also, I would test with a real created local user so I tried to create it on usermagement but when I click on add button, nothing.

#### Applicable Logs (from `/logs/` directory or the Admin page):
There is not log at all, only message on webapp. But I have web browser dev console log when I try to create local user without any reaction.

```

"Error: [orderBy:notarray] http://errors.angularjs.org/1.5.8/orderBy/notarray?p0=%7B%22%24%24state%22%3A%7B%22status%22%3A2%2C%22value%22%3A%7B%22data%22%3A%7B%22statusCode%22%3A500%2C%22message%22%3A%22Something%20went%20horribly%2C%20horribly%20wrong%20while%20servicing%20your%20request.%22%2C%22details%22%3A%22Nancy.RequestExecutionException%3A%20Oh%20noes!%20---%3E%20System.NullReferenceException%3A%20Object%20reference%20not%20set%20to%20an%20instance%20of%20an%20object%5Cn%20%20at%20PlexRequests.UI.Modules.UserManagementModule%2B%3CLoadUsers%3Ed__26.MoveNext%20()%20%5B0x0031a%5D%20in%20%3Ca9ae510d7f6d46549a8435084318a81b%3E%3A0%20%5Cn---%20End%20of%20stack%20trace%20from%20previous%20location%20where%20exception%20was%20thrown%20---%5Cn%20%20at%20System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw%20()%20%5B0x0000c%5D%20in%20%3Cdca3b561b8ad4f9fb10141d81b39ff45%3E%3A0%20%5Cn%20%20at%20System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess%20(System.Threading.Tasks.Task%20task)%20%5B0x0004e%5D%20in%20%3Cdca3b561b8ad4f9fb10141d81b39ff45%3E%3A0%20%5Cn%20%20at%20System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification%20(System.Threading.Tasks.Task%20task)%20%5B0x0002e%5D%20in%20%3Cdca3b561b8ad4f9fb10141d81b39ff45%3E%3A0%20%5Cn%20%20at%20System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd%20(System.Threading.Tasks.Task%20task)%20%5B0x0000b%5D%20in%20%3Cdca3b561b8ad4f9fb10141d81b39ff45%3E%3A0%20%5Cn%20%20at%20System.Runtime.CompilerServices.TaskAwaiter%601%5BTResult%5D.GetResult%20()%20%5B0x00000%5D%20in%20%3Cdca3b561b8ad4f9fb10141d81b39ff45%3E%3A0%20%5Cn%20%20at%20PlexRequests.UI.Modules.UserManagementModule%2B%3C%3C-ctor%3Eb__0_2%3Ed.MoveNext%20()%20%5B0x00060%5D%20in%20%3Ca9ae510d7f6d46549a8435084318a81b%3E%3A0%20%5Cn%20%20%20---%20End%20of%20inner%20exception%20stack%20trace%20---%5Cn%20%20at%20Nancy.NancyEngine.InvokeOnErrorHook%20(Nancy.NancyContext%20context%2C%20Nancy.ErrorPipeline%20pipeline%2C%20System.Exception%20ex)%20%5B0x000bd%5D%20in%20%3C63c44d6f8d7e4f339a987bf9eb94d931%3E%3A0%20%22%7D%2C%22status%22%3A500%2C%22config%22%3A%7B%22method%22%3A%22GET%22%2C%22transformRequest%22%3A%5Bnull%5D%2C%22transformResponse%22%3A%5Bnull%5D%2C%22url%22%3A%22%2Fusermanagement%2Fusers%22%2C%22headers%22%3A%7B%22Accept%22%3A%22application%2Fjson%2C%20text%2Fplain%2C%20*%2F*%22%7D%7D%2C%22statusText%22%3A%22Internal%20Server%20Error%22%7D%7D%7D N/<@http://requests.manfroi.fr/Content/angular.min.js:6:412 Dd/<@http://requests.manfroi.fr/Content/angular.min.js:172:286 anonymous/fn@http://requests.manfroi.fr/Content/angular.min.js line 233 > Function:2:429 u/c<@http://requests.manfroi.fr/Content/angular.min.js:128:453 vf/this.$get Function:2:209 b@http://requests.manfroi.fr/Content/angular.min.js:126:128 Lc[b] Function:2:429 u/c<@http://requests.manfroi.fr/Content/angular.min.js:128:453 vf/this.$get 

```

#### Reproduction Steps:

Just disable authentification for user, set default permission for request movie, open a new private web session (no admin on ombi) and type any username (as auth is disabled) like "user" and try to request a movie.

**Comment by tidusjar** [comment]
Can you please switch to the Early Access Preview branch? This should be fixed in there.

https://ci.appveyor.com/project/tidusjar/requestplex/build/artifacts

Since the Early Access Preview branch is version 2.0 it will require a fresh install. Install into a fresh location and copy over your PlexRequests.sqlite file.

**Comment by xp-1000** [comment]
Hi !
Thanks for your quick answer.
I will test that soon and keep you in touch

**Comment by xp-1000** [comment]
<p>I made a PKGBUILD to install EAP version on my arch and to also migrate to the new Ombi name.<br>
Now it works like a charm, good idea the admin authentification integration!</p>

<p>In my situation, I don't have to enable user authentification but just out of curiosity I tested to create a user and I noticed the same behavior as above (click on add and nothin except an array error in browser console). <br>
Do you think I made a mistake in the installation of ombi or the migration of the database ? or this feature is not ready yet ? <br>
Related question, in the future, could I use the automatic update integrated feature or continue to update from system side ?</p>

<p>In any case all that worked before works fine and usefull new features arrives.
I confess not to be a big entousiast of mono and running it on my OS even if I totally understand the choice for many reasons like cross platform compatibility but you do a realy good job with ombi thanks you.
</p>

**Comment by tidusjar** [comment]
The actual error in the console is more of a warning, it won't affect the functionality so we can ignore that. But do you still have the permission issues?

**Comment by ryanjoachim** [comment]
I was running into this specific issue until recently. I had 2 accounts pulled from Plex - both with the same permissions.

One worked without issue, while the other ran into the same problem showing in this ticket. No matter how I changed the permissions on the non-working account, I was not able to do any requesting.

What finally fixed it for me specificially was changing the name of the account in Plex and waiting for it to update in Ombi. After that, I no longer have issues with that specific account.

**Comment by tidusjar** [comment]
What was the username? Did it have any special characters or anything? Was it similar to another username?

Strange...

**Comment by ryanjoachim** [comment]
In my case the username had a space in it, but the new name doesn't.

**Comment by xp-1000** [comment]
<p>Hi all, sorry for delay</p>
<p>Seems I was not very clear in my answer but since update to early access channel the problem is fixed.</p>
<p>In my situation, there is only one plex attached user (the admin) on ombi and it has/had no problem. it worked in 1.9 (before bug), in 1.10 (during bug) and in v2 early access (after bug resolution).<br>
Only unprivileged user was concerned for 1.10 permission denied bug on request<br>
So my problematic user(s) are just temporal (not created local user or pulled from plex) and used when new user choice a name to log in</p>
<p>In my case (seems different from ryanjoachim because he uses plex users), the permission issue on request by temporal user was fixed by update to early access. So if 1.10 brokes this feature, EAP version repairs it.</p>
<p>The only problem which stays is on feature which did not exist in 1.9 but appears in 1.10, the user management / creation, so it is not a regression this time. In 1.10 I cannot create user (no error, no message) and it is still true in EAP version but it is not my original issue.</p>
<p>Should I open a new case ? Could I help you with making some tests ?</p>

**Comment by xp-1000** [comment]
<p>yes impossible to create user but it is already the case in 1.10.</p>
<p>Error in console :

`Error: $scope.users.some is not a function
controller/$scope.addUser@http://requests.manfroi.fr/Content/app/userManagement/userManagementController.js?v=2.0.0:77:36
anonymous/fn@http://requests.manfroi.fr/Content/angular.min.js line 233 > Function:2:209
b@http://requests.manfroi.fr/Content/angular.min.js:126:128
Lc[b]</<.compile/</</e@http://requests.manfroi.fr/Content/angular.min.js:276:195
vf/this.$get</m.prototype.$eval@http://requests.manfroi.fr/Content/angular.min.js:145:343
vf/this.$get</m.prototype.$apply@http://requests.manfroi.fr/Content/angular.min.js:146:47
Lc[b]</<.compile/</<@http://requests.manfroi.fr/Content/angular.min.js:276:245
n.event.dispatch@http://requests.manfroi.fr/Content/jquery-2.2.1.min.js:3:7464
n.event.add/r.handle@http://requests.manfroi.fr/Content/jquery-2.2.1.min.js:3:5580
  angular.min.js:118:8
	e/< http://requests.manfroi.fr/Content/angular.min.js:118:8
	hf/this.$get</< http://requests.manfroi.fr/Content/angular.min.js:90:220
	vf/this.$get</m.prototype.$apply http://requests.manfroi.fr/Content/angular.min.js:146:94
	Lc[b]</<.compile/</< http://requests.manfroi.fr/Content/angular.min.js:276:245
	n.event.dispatch http://requests.manfroi.fr/Content/jquery-2.2.1.min.js:3:7464
	n.event.add/r.handle`
</p>
<p>I will open new issue, should I close this one ? because it fixed for my case ?</p>

**Comment by SuperPotatoMen** [comment]
Pleas open a new issue for that one

**Comment by xp-1000** [comment]
<p>Hi, done : https://github.com/tidusjar/Ombi/issues/881</p>
<p>I close this one because in my case, 2.0 works fine</p>
<P>Thanks again</p>
